### PR TITLE
add hiasr_api_zh_request.yaml

### PR DESCRIPTION
**Pull request by aluminumbox**
Hi,

we have pushed our api image to oss. Please merge our PR to see evaluate our model.

Thanks

### CODE REVIEW

**Comment by dophist** [comment]
Please make sure all information in model.yaml are valid. You can always re-run `ops/push model xxx` to update your model-image in cloud model-zoo. I'll merge after your fixes. You can give me a notice here when you are done.

**Comment by aluminumbox** [comment]
> Please make sure all information in model.yaml are valid. You can always re-run `ops/push model xxx` to update your model-image in cloud model-zoo. I'll merge after your fixes. You can give me a notice here when you are done.

Thanks for the notice. I have changed model.yaml and pushed to oss.

**Comment by aluminumbox** [comment]
Hi, could you please merge our PR and see how the result comes? @dophist  Thank you

**Comment by dophist** [comment]
Model-image seems ready now.  One more thing, I noticed this is not a public API, is it from Himalaya APP?  To test a private service, I need certain kind of legal term that defines responsibility of data privacy and safety? If there is no such thing, I could even accept a guarantee email from your speech team leader(Lu Heng maybe?), confirming that requested test data will not be stored on your server or maybe worse, leaked.  You guys can send this email to `leaderboard@speechio.ai` , I'll merge after that, and hopefully find some time to finish the benchmark in a week or two. Also remember the results will only be sent to emails listed in your request yaml, you can update that accordingly.

**Comment by dophist** [comment]
Merging, benchmark will be started soon, and results will be sent to requesting email addresses

**Pull request merged**
