### PR TITLE
Add vosk_model_cn_0.1_request.yaml

### PR DESCRIPTION
**Pull request by tonko22**

### CODE REVIEW

**Comment by dophist** [comment]
Seems good, it would be great if you can remove VIM's .swp temp file. Let me know when this request is ready, and I'll merge and start the benchmark.

**Comment by dophist** [comment]
Seems good, it would be great if you can remove VIM's .swp temp file. Let me know when this request is ready, and I'll merge and start the benchmark.

**Comment by tonko22** [comment]
> Seems good, it would be great if you can remove VIM's .swp temp file. Let me know when this request is ready, and I'll merge and start the benchmark.

Done

**Comment by dophist** [comment]
Benchmarking is in progress smoothly, results should be out in 1 day, and will be sent to the email address in request.yaml.

**Pull request merged**
